# Generated by Django 3.2 on 2021-11-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsOfHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=10)),
                ('favourite_food', models.CharField(max_length=15)),
            ],
        ),
    ]
