# Generated by Django 3.2 on 2021-12-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('user_inv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='human.detailsofhuman')),
                ('Song_Name', models.CharField(max_length=1000)),
            ],
        ),
    ]
