# Generated by Django 3.2 on 2021-12-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite_quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
                ('user_f_quotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.detailsofhuman')),
            ],
        ),
    ]
