# Generated by Django 3.2 on 2021-12-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_favourite_quotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favourite_quotes',
            new_name='favouriteQuotes',
        ),
    ]
